### ISSUE TITLE
Optimize DB table structure

### ISSUE THREAD

**Issue by r-brown** [Labs64/PluginPass#10]
Rename columns:

- `number` => `product_number`
- `name` => `plugin_name`
- `validation` => `validation_result`

Add a new column:

- plugin_slug
  - use this column/attribute only to reference plugins
  - use `plugin_name` only to display plugin name in the backend

**Comment by v-rudkovskiy** [comment]
I renamed the columns, but I don’t understand for what we need the plugin slug field?

**Comment by r-brown** [comment]
Use `plugin_slug` column reference registered plugins - not `plugin_name`.
Use `plugin_name` only to display plugins in the table.

**Comment by v-rudkovskiy** [comment]
I have a great solution without having to save the plugin name or slug.
I store a relative plugins folder(column plugin_folder) instead of plugin_name and plugin_slug, for example: some-plugin-folder/some-plugin.php and use the wp function "get_plugins" to get up-to-date information(Name, Description,  e.t.c)  about the plugin.

**Comment by r-brown** [comment]
Review:
- do not use `plugin_folder` as this is not WordPress convention => use `plugin_slug` instead
